// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"time"
)

type User struct {
	ID        uint64
	Username  string
	Email     string
	CreatedAt time.Time
	Password  string
}
