// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"time"
)

type Message struct {
	ID        uint64    `json:"id"`
	SenderID  uint64    `json:"sender_id"`
	RoomID    uint64    `json:"room_id"`
	Contents  string    `json:"contents"`
	CreatedAt time.Time `json:"created_at"`
}

type Permission struct {
	ID   uint64 `json:"id"`
	Name string `json:"name"`
}

type Role struct {
	ID   uint64 `json:"id"`
	Name string `json:"name"`
}

type RolesPermission struct {
	RoleID       uint64 `json:"role_id"`
	PermissionID uint64 `json:"permission_id"`
}

type Room struct {
	ID   uint64  `json:"id"`
	Name *string `json:"name"`
}

type User struct {
	ID        uint64    `json:"id"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
	Password  string    `json:"password"`
}

type UsersRole struct {
	UserID uint64 `json:"user_id"`
	RoleID uint64 `json:"role_id"`
}

type UsersRoom struct {
	UserID uint64 `json:"user_id"`
	RoomID uint64 `json:"room_id"`
}
