// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddUserToRoom(ctx context.Context, arg AddUserToRoomParams) error
	AssignPermissionToRole(ctx context.Context, arg AssignPermissionToRoleParams) error
	AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) error
	AssignRoleToUserInRoom(ctx context.Context, arg AssignRoleToUserInRoomParams) error
	CreateFriendship(ctx context.Context, arg CreateFriendshipParams) (sql.Result, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (sql.Result, error)
	CreateRoom(ctx context.Context, arg CreateRoomParams) (sql.Result, error)
	DeleteFriendship(ctx context.Context, id uint64) error
	DeleteMessage(ctx context.Context, id uint64) error
	DeleteRoom(ctx context.Context, id uint64) error
	DeleteUser(ctx context.Context, id uint64) error
	GetAllRooms(ctx context.Context) ([]Room, error)
	GetCountOfRoom(ctx context.Context, id uint64) (*int32, error)
	GetDMByUsers(ctx context.Context, arg GetDMByUsersParams) (Room, error)
	GetFriendsOfUser(ctx context.Context, arg GetFriendsOfUserParams) ([]User, error)
	GetMessageById(ctx context.Context, id uint64) (Message, error)
	GetMessagesByRoom(ctx context.Context, roomID uint64) ([]Message, error)
	GetPermissions(ctx context.Context) ([]Permission, error)
	GetPermissionsByRole(ctx context.Context, roleID uint64) ([]Permission, error)
	GetPermissionsByUser(ctx context.Context, userID uint64) ([]Permission, error)
	GetRecentMessagesByUserLimited(ctx context.Context, arg GetRecentMessagesByUserLimitedParams) ([]Message, error)
	GetRoleByName(ctx context.Context, name string) (Role, error)
	GetRolesByUser(ctx context.Context, userID uint64) ([]Role, error)
	GetRolesByUserInRoom(ctx context.Context, arg GetRolesByUserInRoomParams) ([]Role, error)
	GetRoomById(ctx context.Context, id uint64) (Room, error)
	GetRoomsByUser(ctx context.Context, userID uint64) ([]Room, error)
	GetUsersByRoom(ctx context.Context, roomID uint64) ([]User, error)
	RemovePermissionFromRole(ctx context.Context, arg RemovePermissionFromRoleParams) error
	RemoveRoleFromUser(ctx context.Context, arg RemoveRoleFromUserParams) error
	RemoveRoleFromUserInRoom(ctx context.Context, arg RemoveRoleFromUserInRoomParams) error
	UpdateRoom(ctx context.Context, arg UpdateRoomParams) error
}

var _ Querier = (*Queries)(nil)
