services:
  backend:
    build:
      context: ./backend
    command: ./backend
    ports:
      - "8080:8080"
    networks:
      - app-network
    profiles:
      - "backend"
    environment:
      DB_HOST: mysql
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - mysql
      - db-migrate

  mysql:
    image: mariadb:lts
    networks:
      - app-network
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./backend/db/mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  sqlc:
    image: sqlc/sqlc
    volumes:
      - ./backend:/backend
    working_dir: /backend
    command: ["generate"]

  db-migrate:
    image: gomicro/goose
    networks:
      - app-network
    depends_on: 
      mysql:
        condition: service_healthy
    environment:
      GOOSE_DRIVER: mysql
      GOOSE_DBSTRING: root:${DB_ROOT_PASSWORD}@tcp(mysql:3306)/${DB_NAME}
    volumes:
      - ./backend/db/migrations:/migrations
    command: ["sh", "-c", "goose ${MIGRATION_DIRECTION:-up} --dir /migrations ${MIGRATION_FILE:-}"]

  frontend-build:
    build: 
      context: ./frontend
      target: export

networks:
  app-network:
    driver: bridge
