services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - app-network
    profiles:
      - "backend"
  frontend-build:
    build: 
      context: ./frontend
      target: export

networks:
  app-network:
    driver: bridge
