FROM golang:1.24-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./

# RUN --mount=type=cache,target=/go/pkg/mod go mod download && go mod tidy
RUN go mod download
RUN go mod tidy

COPY . .

# Install swag and generate the swagger spec.
# RUN go install github.com/swaggo/swag/cmd/swag@latest
# RUN swag init -g src/main.go -o ./swagger

RUN CGO_ENABLED=0 GOOS=linux go build -tags debug -o backend ./src 
# RUN CGO_ENABLED=0 GOOS=linux go build -o backend ./src

# Runtime stage
FROM alpine:latest

WORKDIR /app
COPY --from=builder /app/backend .
# COPY --from=builder /app/swagger ./swagger
EXPOSE 8080
CMD ["./backend"] 
