FROM golang:1.24-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./

RUN --mount=type=cache,target=/go/pkg/mod go mod download && go mod tidy

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -tags debug -o backend ./src 
# RUN CGO_ENABLED=0 GOOS=linux go build -o backend ./src 

# Runtime stage
FROM alpine:latest

WORKDIR /app
COPY --from=builder /app/backend .
EXPOSE 8080
# CMD ["./backend"]
