basePath: /api/v1
host: localhost:8080
info:
  contact:
    email: support@raptorchat.example.com
    name: API Support
    url: http://www.swagger.io/support
  description: This is the API server for RaptorChat.
  termsOfService: http://swagger.io/terms/
  title: RaptorChat API
  version: "1.0"
paths: {}
swagger: "2.0"
