-- +goose Up
-- Rename autogenerated FKs in `friendships`
ALTER TABLE `friendships`
    DROP FOREIGN KEY `friendships_ibfk_1`,
    ADD CONSTRAINT `friendships_first_user_fk`
      FOREIGN KEY (`first_id`) REFERENCES `users`(`id`) ON DELETE CASCADE;
ALTER TABLE `friendships`
    DROP FOREIGN KEY `friendships_ibfk_2`,
    ADD CONSTRAINT `friendships_second_user_fk`
      FOREIGN KEY (`second_id`) REFERENCES `users`(`id`) ON DELETE CASCADE;
ALTER TABLE `friendships`
    DROP FOREIGN KEY `friendships_ibfk_3`,
    ADD CONSTRAINT `friendships_dm_room_fk`
      FOREIGN KEY (`dm_id`) REFERENCES `rooms`(`id`) ON DELETE CASCADE;

-- Rename autogenerated FKs in `invites`
ALTER TABLE `invites`
    DROP FOREIGN KEY `invites_ibfk_1`,
    ADD CONSTRAINT `invites_room_fk`
      FOREIGN KEY (`room_id`) REFERENCES `rooms`(`id`) ON DELETE CASCADE;
ALTER TABLE `invites`
    DROP FOREIGN KEY `invites_ibfk_2`,
    ADD CONSTRAINT `invites_issuer_user_fk`
      FOREIGN KEY (`issuer_id`) REFERENCES `users`(`id`) ON DELETE CASCADE;
ALTER TABLE `invites`
    DROP FOREIGN KEY `invites_ibfk_3`,
    ADD CONSTRAINT `invites_receiver_user_fk`
      FOREIGN KEY (`receiver_id`) REFERENCES `users`(`id`) ON DELETE CASCADE;

-- Rename autogenerated FKs in `roles_permissions`
ALTER TABLE `roles_permissions`
    DROP FOREIGN KEY `roles_permissions_ibfk_1`,
    ADD CONSTRAINT `roles_permissions_role_fk`
      FOREIGN KEY (`role_id`) REFERENCES `roles`(`id`);
ALTER TABLE `roles_permissions`
    DROP FOREIGN KEY `roles_permissions_ibfk_2`,
    ADD CONSTRAINT `roles_permissions_permission_fk`
      FOREIGN KEY (`permission_id`) REFERENCES `permissions`(`id`);

-- Rename generic FKs in `rooms_users_roles`
ALTER TABLE `rooms_users_roles`
    DROP FOREIGN KEY `fk_rur_role`,
    ADD CONSTRAINT `rooms_users_roles_role_fk`
      FOREIGN KEY (`role_id`) REFERENCES `roles`(`id`) ON DELETE CASCADE;
ALTER TABLE `rooms_users_roles`
    DROP FOREIGN KEY `fk_rur_room`,
    ADD CONSTRAINT `rooms_users_roles_room_fk`
      FOREIGN KEY (`room_id`) REFERENCES `rooms`(`id`) ON DELETE CASCADE;
ALTER TABLE `rooms_users_roles`
    DROP FOREIGN KEY `fk_rur_user`,
    ADD CONSTRAINT `rooms_users_roles_user_fk`
      FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE;

-- Rename autogenerated FKs in `users_roles`
ALTER TABLE `users_roles`
    DROP FOREIGN KEY `users_roles_ibfk_1`,
    ADD CONSTRAINT `users_roles_user_fk`
      FOREIGN KEY (`user_id`) REFERENCES `users`(`id`);
ALTER TABLE `users_roles`
    DROP FOREIGN KEY `users_roles_ibfk_2`,
    ADD CONSTRAINT `users_roles_role_fk`
      FOREIGN KEY (`role_id`) REFERENCES `roles`(`id`);

-- +goose Down
-- Revert FKs in `friendships` to original autogenerated names
ALTER TABLE `friendships`
    DROP FOREIGN KEY `friendships_first_user_fk`,
    ADD CONSTRAINT `friendships_ibfk_1`
      FOREIGN KEY (`first_id`) REFERENCES `users`(`id`) ON DELETE CASCADE;
ALTER TABLE `friendships`
    DROP FOREIGN KEY `friendships_second_user_fk`,
    ADD CONSTRAINT `friendships_ibfk_2`
      FOREIGN KEY (`second_id`) REFERENCES `users`(`id`) ON DELETE CASCADE;
ALTER TABLE `friendships`
    DROP FOREIGN KEY `friendships_dm_room_fk`,
    ADD CONSTRAINT `friendships_ibfk_3`
      FOREIGN KEY (`dm_id`) REFERENCES `rooms`(`id`) ON DELETE CASCADE;

-- Revert FKs in `invites` to original autogenerated names
ALTER TABLE `invites`
    DROP FOREIGN KEY `invites_room_fk`,
    ADD CONSTRAINT `invites_ibfk_1`
      FOREIGN KEY (`room_id`) REFERENCES `rooms`(`id`) ON DELETE CASCADE;
ALTER TABLE `invites`
    DROP FOREIGN KEY `invites_issuer_user_fk`,
    ADD CONSTRAINT `invites_ibfk_2`
      FOREIGN KEY (`issuer_id`) REFERENCES `users`(`id`) ON DELETE CASCADE;
ALTER TABLE `invites`
    DROP FOREIGN KEY `invites_receiver_user_fk`,
    ADD CONSTRAINT `invites_ibfk_3`
      FOREIGN KEY (`receiver_id`) REFERENCES `users`(`id`) ON DELETE CASCADE;

-- Revert FKs in `roles_permissions` to original autogenerated names
ALTER TABLE `roles_permissions`
    DROP FOREIGN KEY `roles_permissions_role_fk`,
    ADD CONSTRAINT `roles_permissions_ibfk_1`
      FOREIGN KEY (`role_id`) REFERENCES `roles`(`id`);
ALTER TABLE `roles_permissions`
    DROP FOREIGN KEY `roles_permissions_permission_fk`,
    ADD CONSTRAINT `roles_permissions_ibfk_2`
      FOREIGN KEY (`permission_id`) REFERENCES `permissions`(`id`);

-- Revert FKs in `rooms_users_roles` to original names
ALTER TABLE `rooms_users_roles`
    DROP FOREIGN KEY `rooms_users_roles_role_fk`,
    ADD CONSTRAINT `fk_rur_role`
      FOREIGN KEY (`role_id`) REFERENCES `roles`(`id`) ON DELETE CASCADE;
ALTER TABLE `rooms_users_roles`
    DROP FOREIGN KEY `rooms_users_roles_room_fk`,
    ADD CONSTRAINT `fk_rur_room`
      FOREIGN KEY (`room_id`) REFERENCES `rooms`(`id`) ON DELETE CASCADE;
ALTER TABLE `rooms_users_roles`
    DROP FOREIGN KEY `rooms_users_roles_user_fk`,
    ADD CONSTRAINT `fk_rur_user`
      FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE;

-- Revert FKs in `users_roles` to original autogenerated names
ALTER TABLE `users_roles`
    DROP FOREIGN KEY `users_roles_user_fk`,
    ADD CONSTRAINT `users_roles_ibfk_1`
      FOREIGN KEY (`user_id`) REFERENCES `users`(`id`);
ALTER TABLE `users_roles`
    DROP FOREIGN KEY `users_roles_role_fk`,
    ADD CONSTRAINT `users_roles_ibfk_2`
      FOREIGN KEY (`role_id`) REFERENCES `roles`(`id`);
